### ISSUE TITLE
Running sdfit on mac

### ISSUE THREAD

**Issue by thecrimplord** [hotgluebanjo/sunday-trained#1]
Hey,
Im having issue running this on my mac, is there any additional advice or instruction you could offer. I'd use the -h but I'm unable to get it working. any advice would be awesome,  I'm new to coding so apologies for the lack of detail. Just wondering what the basics are to get this running properly.
thanks

**Comment by hotgluebanjo** [comment]
Hi. Perhaps you need to make it executable?

```
chmod +x ./sdfit
```

Mac also prevents some apps from unidentified developers from running, though I'm not sure that applies here. Beyond that, not sure.

**Comment by thecrimplord** [comment]
Hey Hotgluebanjo,
apologies for the vagueness of my last message, appreciate the reply, I
didn't even realise I needed to do this (chmod +x), if you have a minute
may I ask if you could give a brief step by step rundown on how to install
and get your programme running, I'd love to try out what you've
developed but with only a basic python understanding it would take me a
while to figure out where to begin, if you could point me and other users
like me in the right direction that'd be amazing.
thanks heaps

**Comment by thecrimplord** [comment]
Hey Hotgluebanjo,
apologies for the vagueness of my last message, appreciate the reply, I
didn't even realise I needed to do this (chmod +x), if you have a minute
may I ask if you could give a brief step by step rundown on how to install
and get your programme running, I'd love to try out what you've
developed but with only a basic python understanding it would take me a
while to figure out where to begin, if you could point me in the right direction that'd be amazing.
thanks heaps

**Comment by hotgluebanjo** [comment]
Head to the [releases](https://github.com/hotgluebanjo/sdfit/releases/latest) and download the Mac build. Open a terminal and [`cd`](https://www.educative.io/answers/what-is-cd-in-linux) to the download directory. Then extract with:

```
tar -xf ./sdfit-0.2.0-macos.tar.gz
```
`cd` into the directory containing the binary (should now be `./release/macos`) and make it executable, as mentioned above. Try running it with `./sdfit -h`.

There's no need to install it; it's entirely portable. If you want, you can install it by putting it in a bin directory in your path.

**Comment by hotgluebanjo** [comment]
@thecrimplord Your comment appears to have vanished? I'll close this for now since this isn't an issue with the tool. Feel free to reopen if you find any.
